version: "3"

services:

  web-server:
    build: ./web_server
    container_name: web_server
    restart: always
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 5000:80
      